spring.application.name=cinema

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=rapchieuphim;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456789

# ===============================
# JPA / HIBERNATE CONFIG    
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Ép Hibernate sử dụng chính xác tên bảng và tên cột như đã khai báo trong Java
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#config spring security
spring.security.user.name=sa
spring.security.user.password=123456789

###
#config jwt
jwt.base64-secret=TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
#expiration : 1 day (seconds = 24 * 60 * 60)
# 100 days
jwt.access-token-validity-in-seconds=8640000
jwt.refresh-token-validity-in-seconds=8640000
#
###
# Bật chế độ soi chiếu mọi hoạt động của Spring Security
# logging.level.org.springframework.security=TRACE
# logging.level.org.springframework.web=DEBUG

logging.level.org.hibernate.SQL=DEBUG


cloudinary.cloud-name=ddog2qhlv
cloudinary.api-key=652582852549581
cloudinary.api-secret=2DV2OfKtq-T3baQdaSzY2XZtyPs

# ===============================
# CẤU HÌNH KIẾN TRÚC PHÂN TÁN
# ===============================
# Mã cơ sở của Server hiện tại (Trung tâm là KV_00)

# Anh em s?a d�ng n�y v? ?�ng t�n c?a m�nh (select trong b?ng rap)
app.cinema.ma-co-so=KV_00

# C�i n�y gi? nguy�n
app.cinema.linked-server=MAIN-SERVER

# Địa chỉ IP của Máy chủ Trung tâm để gọi API khi đặt vé
# (Thay 192.168.1.100 bằng IP LAN hoặc Domain thực tế của máy chủ)
app.cinema.center-url=http://192.168.1.100:8080